source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


platform :ios, '11.0'
inhibit_all_warnings!

target 'flutter_boost_native' do
  
install_all_flutter_pods(flutter_application_path)

pod 'Reveal-SDK', '24', :configurations => ['Debug']

end

