source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

flutter_application_path = '../flutter_one'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


platform :ios, '11.0'
inhibit_all_warnings!

target 'NativeApp' do
  
install_all_flutter_pods(flutter_application_path)

pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage'


end

